O.opera = {
  title: 'THE BARBER OF SEVILLE', lang: 'it',
  tempo: 152,
  root: 0, mode: 'major',
  cast: {
    a: { color: '#e8891c', size: 1.0, voice: 'tenor' },
    b: { color: '#f2a8c4', size: 0.7, voice: 'soprano' },
    c: { color: '#6b4226', size: 1.6, voice: 'bass' },
  },
  motif: ['1 2 3 5 4 2 1', 'xxxxxxx-'],
  chords: 'i v i v',
  room: [3000, 0.15],
  intro: 4.2, outro: 5,
  score: [
    [0, 'appear', 'a', { cell: [1, 4] }],
    [0, 'roomChange', null, { cutoff: 3000, feedback: 0.15, dur: 0.3 }],
    [0, 'cue', null, { text: 'IL BARBIERE.', hold: 1.6 }],
    [2.4, 'pulse', 'a', { beats: 2, amount: 1.15 }],

    ['1.1', 'path', 'a', { cells: [[1, 1], [7, 1], [7, 7], [1, 7]], stepDur: 0.18, trail: true }],
    ['1.1', 'sing', 'a', {}],
    ['1.1', 'cue', null, { text: 'FIGARO!', hold: 1 }],
    ['2.1', 'dash', 'a', { cells: [[1, 7], [4, 4], [7, 1]], speed: 2.5 }],
    ['2.1', 'sing', 'a', {}],
    ['3.1', 'path', 'a', { cells: [[7, 1], [1, 7], [4, 4]], stepDur: 0.18, trail: true }],
    ['3.1', 'sing', 'a', {}],
    ['4.1', 'dash', 'a', { cells: [[4, 4], [1, 1], [7, 7]], speed: 2.5 }],
    ['4.1', 'sing', 'a', {}],
    ['5.1', 'sing', 'a', {}],
    ['5.1', 'pulse', 'a', { beats: 1, amount: 1.1 }],

    ['6.1', 'appear', 'c', { cell: [4, 4] }],
    ['6.1', 'freeze', 'c', { dur: 3.1 }],
    ['6.1', 'sing', 'c', { transform: [['frag', 3], ['aug']] }],
    ['7.1', 'sing', 'c', { transform: [['frag', 3], ['aug']] }],
    ['7.1', 'orbit', 'a', { center: [4, 4], radius: 2, turns: 1 }],

    ['8.1', 'enter', 'b', { edge: 'top', to: [4, 1], dur: 0.5 }],
    ['8.3', 'approach', 'b', { target: 'a', dur: 0.9 }],
    ['8.1', 'sing', 'b', { transform: ['tr', 12] }],
    ['8.1', 'cue', null, { text: 'LINDORO!', hold: 1 }],
    ['9.1', 'sing', 'b', { transform: ['tr', 12] }],
    ['9.3', 'sing', 'a', {}],

    ['10.1', 'weave', 'a', { targets: ['b', 'c'], stepDur: 0.2 }],
    ['10.1', 'sing', 'a', { transform: 'dim' }],
    ['10.1', 'crescendo', null, { to: 0.6, dur: 1.5 }],
    ['11.1', 'weave', 'a', { targets: ['c', 'b'], stepDur: 0.18 }],
    ['11.1', 'sing', 'a', { transform: [['dim'], ['dim']] }],
    ['11.1', 'sing', 'c', { transform: [['frag', 3], ['aug']] }],
    ['12.1', 'sing', 'b', { transform: ['tr', 12] }],
    ['12.1', 'crescendo', null, { to: 0.75, dur: 1.5 }],
    ['12.1', 'dash', 'a', { cells: [[4, 4], [7, 7], [1, 1]], speed: 3 }],
    ['13.1', 'sing', 'a', { transform: [['dim'], ['dim']] }],
    ['13.1', 'stutter', 'a', { beats: 2 }],
    ['14.1', 'sing', 'c', { transform: [['frag', 3], ['aug']] }],
    ['14.3', 'sing', 'b', { transform: ['tr', 12] }],
    ['15.1', 'scatter', null, { actors: ['b', 'c'], from: [4, 4], dur: 0.4 }],
    ['15.1', 'sing', 'a', { transform: [['dim'], ['dim']] }],
    ['15.1', 'crescendo', null, { to: 0.88, dur: 1.5 }],
    ['16.1', 'echoVoice', 'a', { delay: 0.15, voice: 'arp' }],
    ['16.1', 'sing', 'a', { transform: 'frag' }],
    ['17.1', 'sing', 'a', { transform: [['dim'], ['dim']] }],
    ['17.1', 'dash', 'a', { cells: [[1, 1], [7, 1], [7, 7], [1, 7]], speed: 3.5 }],

    ['18.1', 'freeze', 'a', { dur: 1.2 }],
    ['18.1', 'freeze', 'b', { dur: 1.2 }],
    ['18.1', 'freeze', 'c', { dur: 1.2 }],
    ['18.1', 'silence', null, { dur: 1.2 }],
    ['18.1', 'cue', null, { text: 'ZITTO!', hold: 1 }],

    ['19.1', 'pulse', 'c', { beats: 1, amount: 1.4 }],
    ['19.1', 'roomChange', null, { cutoff: 700, feedback: 0.65, dur: 0.05 }],
    ['19.1', 'chord', 'a', { numeral: 'v', dur: 0.5, voice: 'bass' }],
    ['19.2', 'roomChange', null, { cutoff: 3000, feedback: 0.15, dur: 0.05 }],
    ['19.1', 'cue', null, { text: 'BRAVO!', hold: 1 }],

    ['20.1', 'dash', 'a', { cells: [[4, 4], [1, 1], [7, 1], [7, 7], [1, 7], [4, 4]], speed: 4 }],
    ['20.1', 'scatter', null, { actors: ['b', 'c'], from: [4, 4], dur: 0.5 }],
    ['20.1', 'sing', 'a', {}],
    ['20.1', 'crescendo', null, { to: 1, dur: 2.5 }],
    ['20.1', 'cue', null, { text: 'FACTOTUM!', hold: 1 }],
    ['21.1', 'sing', 'b', { transform: ['tr', 12] }],
    ['21.1', 'sing', 'c', {}],
    ['22.1', 'chord', 'a', { numeral: 'i', dur: 0.5, voice: 'bass' }],
    ['22.1', 'pulse', 'a', { beats: 1, amount: 1.2 }],
    ['22.3', 'chord', 'a', { numeral: 'v', dur: 0.5, voice: 'tenor' }],
    ['23.1', 'chord', 'a', { numeral: 'i', dur: 0.4, voice: 'bass' }],

    ['o0', 'silence', null, { dur: 0.2 }],
    ['o0', 'dash', 'a', { cells: [[4, 4], [1, 4]], speed: 3 }],
    ['o0', 'exit', 'c', { edge: 'bottom', speed: 2 }],
    ['o0', 'dissolve', 'b', { dur: 1 }],
    ['o0.2', 'crescendo', null, { to: 0.85, dur: 1.3 }],
  ],
};
