O.opera = {
  title: 'DIDO AND AENEAS', lang: 'en',
  tempo: 56,
  root: 7, mode: 'minor',
  cast: {
    a: { color: '#8b5cf6', size: 1.6, voice: 'soprano' },
    b: { color: '#cbd5e1', size: 0.6, voice: 'soprano' },
    c: { color: '#111827', size: 1, voice: 'bass' },
  },
  motif: ['1 7- 6- 5-', 'x-x-x-x-'],
  chords: 'i iv vi v',
  room: [700, 0.4],
  intro: 8, outro: 8,
  score: [
    [0, 'roomChange', null, { cutoff: 700, feedback: 0.4, dur: 0.3 }],
    [0, 'fillRing', null, { center: [4, 4], ring: 4, color: '#cbd5e1' }],
    [0.3, 'fillColumn', null, { col: 4, stepDur: 0.7 }],
    [0.3, 'sing', 'c', {}],
    [4.6, 'sing', 'c', {}],

    ['1.1', 'cue', null, { text: 'REMEMBER ME.', hold: 1.8 }],
    ['1.1', 'appear', 'a', { cell: [4, 0] }],
    ['1.1', 'sing', 'a', { transform: ['tr', 12] }],
    ['1.1', 'sing', 'c', {}],
    ['1.1', 'sink', 'a', { rows: 4, stepDur: 2 }],
    ['2.1', 'sing', 'c', {}],
    ['3.1', 'sing', 'c', {}],
    ['4.1', 'sing', 'c', {}],

    ['5.1', 'appear', 'b', { cell: [0, 4], scale: 0.6 }],
    ['5.1', 'sing', 'b', { transform: [['frag', 2], ['dim']] }],
    ['5.1', 'flicker', 'b', { beats: 4, amount: 0.4 }],
    ['5.1', 'sing', 'c', {}],
    ['6.1', 'sing', 'c', {}],

    ['7.1', 'cue', null, { text: 'BUT AH.', hold: 1.6 }],
    ['7.1', 'sing', 'a', { transform: [['tr', 12], ['aug']] }],
    ['7.1', 'crescendo', null, { to: 0.85, dur: 4 }],
    ['7.1', 'sink', 'a', { rows: 4, stepDur: 2 }],
    ['7.1', 'shrink', 'a', { to: 0.5, dur: 4 }],
    ['7.1', 'sing', 'c', {}],
    ['8.1', 'sing', 'c', {}],

    ['9.1', 'cue', null, { text: 'FORGET MY FATE.', hold: 2 }],
    ['9.1', 'silence', null, { dur: 0.3 }],
    ['9.1', 'dissolve', 'a', { dur: 1.5 }],
    ['9.1', 'roomChange', null, { cutoff: 900, feedback: 0.7, dur: 3 }],
    ['9.1', 'sing', 'c', {}],

    ['10.1', 'colourWash', 'grid', { color: '#1e1b24', dur: 3 }],
    ['10.1', 'dissolve', 'b', { dur: 2 }],
    ['10.1', 'sing', 'c', {}],
    ['11.1', 'sing', 'c', {}],

    ['12.1', 'sing', 'c', { voice: 'arp' }],
    ['13.1', 'sing', 'c', { voice: 'arp' }],
    ['14.1', 'sing', 'c', { voice: 'arp' }],

    ['o0', 'sing', 'c', { voice: 'arp' }],
    ['o0.2', 'roomChange', null, { cutoff: 700, feedback: 0.4, dur: 6 }],
    ['o0.5', 'colourWash', 'grid', { color: '#cbd5e1', dur: 5 }],
    ['o1', 'fillColumn', null, { col: 4, stepDur: 0.6 }],
    ['o2', 'appear', 'a', { cell: [4, 8], scale: 0.4 }],
    ['o2.2', 'rise', 'a', { rows: 8, stepDur: 0.5 }],
    ['o2.2', 'grow', 'a', { to: 1.6, dur: 4 }],
    ['o6.5', 'dissolve', 'a', { dur: 1.4 }],
  ],
};
