/* Gesture metadata for the playground and docs/engine-api.md. Plain data,
   never concatenated into the engine. Mirrors the vocabulary table in
   docs/visual-guide.md exactly - nothing here that isn't in O.G. */
module.exports = {
  // ---- Hero ----
  hop: { family: 'hero', doc: 'travel to a cell with a pluck lighting the actor', actors: 1,
    params: { to: [[4, 4], 'cell'], dur: [0.35, 0.1, 1], semi: [null, [-24, 24]] } },
  bounce: { family: 'hero', doc: 'a quick scale bounce in place, lit by a note', actors: 1,
    params: { dur: [0.3, 0.1, 1], amount: [1.3, 1, 2] } },
  flee: { family: 'hero', doc: 'a fast fearful move to a cell, dimmer light', actors: 1,
    params: { to: [[4, 4], 'cell'], dur: [0.3, 0.1, 1] } },
  pulse: { family: 'hero', doc: 'heartbeat: a drum flash on the actor, beat by beat', actors: 1,
    params: { beats: [2, 1, 8] } },
  grow: { family: 'hero', doc: 'scale up, power or love', actors: 1,
    params: { to: [1.6, 0.5, 3], dur: [1, 0.1, 4] } },
  shrink: { family: 'hero', doc: 'scale down, fear or death', actors: 1,
    params: { to: [0.4, 0, 1.5], dur: [1, 0.1, 4] } },
  pop: { family: 'hero', doc: 'pop into place with a pluck', actors: 1,
    params: { dur: [0.3, 0.1, 1], scale: [1, 0.2, 2] } },
  fade: { family: 'hero', doc: 'fade toward dusk on a long release', actors: 1,
    params: { dur: [2, 0.5, 5] } },

  // ---- Travel ----
  chase: { family: 'travel', doc: 'an arp lights a ring, cell by cell, in order', actors: 0,
    params: { center: [[4, 4], 'cell'], ring: [4, 0, 6], numeral: ['i', 'numeral'], dur: [2, 0.5, 5], rate: [16, 4, 40], light: ['sky', 'text'] } },
  comet: { family: 'travel', doc: 'a lit path with a fading tail', actors: 0,
    params: { cells: [[], 'text'], numeral: ['i', 'numeral'], dur: [2, 0.5, 5], rate: [10, 4, 30], light: ['sky', 'text'] } },
  scan: { family: 'travel', doc: 'a row or column lit in sequence', actors: 0,
    params: { row: [null, [0, 8]], col: [null, [0, 8]], numeral: ['i', 'numeral'], dur: [1.5, 0.5, 4], light: ['bulb', 'text'], full: [false, ['false', 'true']] } },
  draw: { family: 'travel', doc: 'an arbitrary list of cells lit in order', actors: 0,
    params: { cells: [[], 'text'], numeral: ['i', 'numeral'], dur: [2, 0.5, 5], light: ['violet', 'text'] } },
  spiral: { family: 'travel', doc: 'rings lit outward or inward from a centre', actors: 0,
    params: { center: [[4, 4], 'cell'], rings: [4, 1, 6], inward: [false, ['false', 'true']], light: ['mint', 'text'] } },
  orbit: { family: 'travel', doc: 'an actor circles a fixed point', actors: 1,
    params: { center: [[4, 4], 'cell'], radius: [1.5, 0.5, 3], turns: [1, 1, 4] } },

  // ---- Fill ----
  fillTop: { family: 'fill', doc: 'the top rows lit together, one arp', actors: 0,
    params: { rows: [2, 1, 4], numeral: ['i', 'numeral'], light: ['sky', 'text'], full: [false, ['false', 'true']] } },
  fillCentre: { family: 'fill', doc: 'a disk around the centre lit together', actors: 0,
    params: { radius: [1, 0, 4], numeral: ['i', 'numeral'], light: ['mint', 'text'], full: [false, ['false', 'true']] } },
  fillEdge: { family: 'fill', doc: 'the outer ring lit together', actors: 0,
    params: { numeral: ['i', 'numeral'], light: ['violet', 'text'], full: [false, ['false', 'true']] } },
  stripe: { family: 'fill', doc: 'a single row or column lit together', actors: 0,
    params: { row: [null, [0, 8]], col: [null, [0, 8]], light: ['lemon', 'text'], full: [false, ['false', 'true']] } },
  map: { family: 'fill', doc: 'an arbitrary shape lit together', actors: 0,
    params: { cells: [[], 'text'], light: ['coral', 'text'] } },

  // ---- Burst ----
  flash: { family: 'burst', doc: 'a drum hit lights a set of cells at once', actors: 0,
    params: { cells: [[], 'text'], light: ['lemon', 'text'], pattern: ['hat', ['kick', 'snare', 'hat', 'heartbeat']] } },
  explode: { family: 'burst', doc: 'successive rings flash outward from a centre', actors: 0,
    params: { center: [[4, 4], 'cell'], rings: [3, 1, 6], light: ['coral', 'text'] } },
  ripple: { family: 'burst', doc: 'softer concentric rings, staggered outward', actors: 0,
    params: { center: [[4, 4], 'cell'], rings: [4, 1, 6], light: ['sky', 'text'], full: [false, ['false', 'true']] } },
  sparkle: { family: 'burst', doc: 'a few random cells flash over a duration', actors: 0,
    params: { count: [6, 1, 20], dur: [1.2, 0.3, 3], light: ['bulb', 'text'] } },
  glitter: { family: 'burst', doc: 'many random cells shimmer as one arp', actors: 0,
    params: { count: [14, 4, 30], dur: [1.6, 0.5, 4], light: ['lemon', 'text'] } },
  confetti: { family: 'burst', doc: 'a reward burst across the seven-hue rainbow', actors: 0,
    params: { count: [12, 4, 30], dur: [1.6, 0.5, 4] } },

  // ---- Colour: the seven-hue exception ----
  rainbowCentre: { family: 'colour', doc: 'rings outward, each its own hue of the rainbow', actors: 0,
    params: { rings: [4, 1, 6], gap: [0.12, 0.02, 0.4], full: [false, ['false', 'true']] } },
  rainbowCycle: { family: 'colour', doc: 'the whole grid steps through the seven hues', actors: 0,
    params: { dur: [3.5, 1, 8], full: [false, ['false', 'true']] } },
  jumpCut: { family: 'colour', doc: 'the background cuts to a light, no transition', actors: 0,
    params: { light: [null, 'text'] } },

  // ---- Ending ----
  decay: { family: 'ending', doc: "an actor's last note sustains then fades", actors: 1,
    params: { dur: [3, 1, 8] } },
  burn: { family: 'ending', doc: 'an ember-slow fade with a low noise swell', actors: 1,
    params: { dur: [2.5, 1, 6] } },
  snow: { family: 'ending', doc: 'soft random flecks falling into dusk', actors: 0,
    params: { count: [10, 2, 24], dur: [3, 1, 8], light: ['sky', 'text'] } },
  soloFade: { family: 'ending', doc: 'the hero alone, fading to dusk', actors: 1,
    params: { dur: [4, 1, 10] } },

  // ---- Sound-only ----
  hold: { family: 'sound', doc: "sustain the actor's last note; its disc follows the held voice", actors: 1,
    params: { dur: [3, 0.5, 10], vol: [0.15, 0, 0.4] } },
  sing: { family: 'sound', doc: "play the motif on the actor's voice; its disc follows every note", actors: 1,
    params: { transform: [null, ['inv', 'retro', 'aug', 'dim', 'frag', 'mi', 'ma']], vol: [0.15, 0, 0.4] } },
  chord: { family: 'sound', doc: 'play a chord, bass plus one colour note', actors: 1,
    params: { numeral: ['i', 'numeral'], dur: [1.5, 0.2, 4], voice: ['bass', ['bass', 'tenor', 'soprano', 'arp']] } },
  arp: { family: 'sound', doc: 'a chord arpeggio, optionally lighting a list of cells', actors: 0,
    params: { numeral: ['i', 'numeral'], dur: [2, 0.5, 6], rate: [20, 8, 60], cells: [[], 'text'], light: [null, 'text'] } },
  drum: { family: 'sound', doc: 'a percussion hit, optionally lighting cells as a flash', actors: 0,
    params: { pattern: ['kick', ['kick', 'snare', 'hat', 'heartbeat']], vol: [0.15, 0, 0.4], cells: [[], 'text'] } },
  silence: { family: 'sound', doc: 'mute the room for a duration, then restore', actors: 0,
    params: { dur: [0.25, 0.05, 2] } },
  crescendo: { family: 'sound', doc: 'swell the master gain over a span', actors: 0,
    params: { to: [0.9, 0, 1], dur: [2, 0.2, 6] } },
  ritardando: { family: 'sound', doc: "ease the clock's tempo into a cadence, then release", actors: 0,
    params: { stretch: [1.15, 1, 2], beats: [1, 1, 4] } },
  room: { family: 'sound', doc: "move the room's delay/filter toward a new state", actors: 0,
    params: { cutoff: [1200, 200, 4000], feedback: [0.45, 0, 0.8], dur: [1.5, 0.1, 5] } },

  // ---- Text ----
  cue: { family: 'text', doc: 'the original cue: typed lower-third, letterboxed reveal', actors: 0,
    params: { text: ['', 'text'], hold: [1.6, 0.2, 4] } },

  // ---- Camera ----
  closeUp: { family: 'camera', doc: "hard-zoom until the actor's disc fills half the viewport", actors: 1,
    params: { dur: [0.12, 0.05, 0.5] } },
  snapBack: { family: 'camera', doc: 'instant return to the resting frame', actors: 0,
    params: { dur: [0.12, 0.05, 0.5] } },
  shake: { family: 'camera', doc: 'short high-frequency camera jitter', actors: 0,
    params: { amount: [6, 1, 20], dur: [0.3, 0.1, 1] } },
};
