/* Phase 1: gesture metadata for the playground and docs/engine-api.md.
   Plain data, never concatenated into the engine. Every gesture in O.G has
   an entry. Each param is [default, control]: control is [min,max] for a
   number, an array of strings for a select, 'cell' for a grid cell, 'text'
   for a string, or 'numeral' for a chord numeral. */
module.exports = {
  // ---- Phase 0: the ranked twenty ----
  cue: { family: 'text', doc: 'typed lower-third caption, letterboxed reveal', actors: 0,
    params: { text: ['', 'text'], hold: [1.6, 0.2, 4] } },
  sing: { family: 'sound', doc: "play the motif on the actor's voice, optional transform", actors: 1,
    params: { transform: [null, ['inv', 'retro', 'aug', 'dim', 'frag', 'mi', 'ma']], vol: [0.15, 0, 0.4] } },
  crescendo: { family: 'sound', doc: 'swell the master gain over a span', actors: 0,
    params: { to: [0.9, 0, 1], dur: [2, 0.2, 6] } },
  silence: { family: 'sound', doc: 'mute the room for a duration, then restore', actors: 0,
    params: { dur: [0.25, 0.05, 2] } },
  hold: { family: 'time', doc: "actor's last note sustains unchanged for a duration", actors: 1,
    params: { dur: [2, 0.2, 6] } },
  freeze: { family: 'state', doc: 'actor holds its current pose exactly', actors: 1,
    params: { dur: [1, 0.1, 4] } },
  chord: { family: 'sound', doc: 'play a chord, bass plus one colour note', actors: 1,
    params: { numeral: ['i', 'numeral'], dur: [1.5, 0.2, 4], voice: ['bass', ['bass', 'tenor', 'soprano', 'arp']] } },
  shrink: { family: 'scale', doc: 'scale down smoothly, fear or death', actors: 1,
    params: { to: [0.4, 0, 1.5], dur: [1, 0.1, 4] } },
  enter: { family: 'entrance', doc: 'slide in from a grid edge to a cell', actors: 1,
    params: { edge: ['left', ['left', 'right', 'top', 'bottom']], to: [[2, 4], 'cell'], dur: [0.6, 0.1, 3] } },
  flicker: { family: 'state', doc: 'rapid small unstable opacity change', actors: 1,
    params: { beats: [4, 1, 12], amount: [0.3, 0, 1] } },
  arpChorus: { family: 'sound', doc: 'chord as fast arpeggio, chorus lights faintly', actors: 0,
    params: { numeral: ['i', 'numeral'], dur: [2, 0.2, 6], rate: [45, 8, 60] } },
  ritardando: { family: 'sound', doc: "ease the clock's tempo into a cadence, then release", actors: 0,
    params: { stretch: [1.15, 1, 2], beats: [1, 1, 4] } },
  approach: { family: 'relationship', doc: 'close the distance to a target actor over a duration', actors: 1,
    params: { target: [null, ['a', 'b', 'c']], dur: [1, 0.1, 4] } },
  roomChange: { family: 'sound', doc: "move the room's delay/filter toward a new state", actors: 0,
    params: { cutoff: [1200, 200, 4000], feedback: [0.45, 0, 0.8], dur: [1.5, 0.1, 5] } },
  dissolve: { family: 'entrance', doc: 'shrink and fade to nothing in place', actors: 1,
    params: { dur: [1.2, 0.1, 4] } },
  pulse: { family: 'scale', doc: 'rhythmic brief scale beat, heartbeat-like', actors: 1,
    params: { beats: [2, 1, 8], amount: [1.25, 1, 2] } },
  rise: { family: 'motion', doc: 'travel upward one row per beat, unhurried', actors: 1,
    params: { rows: [2, 1, 8], stepDur: [0.8, 0.1, 2] } },
  grow: { family: 'scale', doc: 'scale up smoothly, power or love', actors: 1,
    params: { to: [1.6, 0.5, 3], dur: [1, 0.1, 4] } },
  appear: { family: 'entrance', doc: 'pop into existence at a cell, no travel', actors: 1,
    params: { cell: [null, 'cell'], scale: [1, 0.2, 2] } },
  eclipse: { family: 'relationship', doc: "one actor's move closes down and snaps shut onto another", actors: 1,
    params: { target: [null, ['a', 'b', 'c']], dur: [0.6, 0.1, 2], numeral: ['v', 'numeral'] } },

  // ---- Phase 0.5: the purple section ----
  ascend: { family: 'setpiece', doc: 'four ascending chords, ring pulses and the room opening', actors: 0,
    params: { numerals: [['i', 'iv', 'v', 'i+'], 'text'], gap: [2.0, 0.5, 4], hue: [272, 0, 360], hueStep: [5, 0, 30] } },

  // ---- Phase 1: the remaining 32 ----
  exit: { family: 'entrance', doc: 'travel off an edge and vanish, optionally rocketing', actors: 1,
    params: { edge: ['right', ['left', 'right', 'top', 'bottom']], speed: [1, 0.5, 3] } },
  reveal: { family: 'entrance', doc: "swap an actor's colour/identity at a cell, mid-beat", actors: 1,
    params: { to: [null, 'cell'], dur: [0.3, 0.1, 1], color: [null, 'text'] } },
  path: { family: 'motion', doc: 'travel a list of cells in order, optional trail', actors: 1,
    params: { cells: [[], 'text'], stepDur: [0.4, 0.1, 1.5], trail: [false, ['false', 'true']] } },
  orbit: { family: 'motion', doc: 'circle a fixed point', actors: 1,
    params: { center: [[4, 4], 'cell'], radius: [1.5, 0.5, 3], turns: [1, 1, 4] } },
  wander: { family: 'motion', doc: 'undirected drift to a random nearby cell', actors: 1,
    params: { range: [2, 1, 4], dur: [1, 0.2, 3] } },
  dash: { family: 'motion', doc: 'fast multi-point path with an arp burst per corner', actors: 1,
    params: { cells: [[], 'text'], speed: [2, 0.5, 4] } },
  weave: { family: 'motion', doc: "path threading between other actors' current cells", actors: 1,
    params: { targets: [[], 'text'], stepDur: [0.3, 0.1, 1] } },
  sink: { family: 'motion', doc: 'travel downward one row per beat', actors: 1,
    params: { rows: [2, 1, 8], stepDur: [0.8, 0.1, 2] } },
  scatter: { family: 'motion', doc: 'a group of actors flee outward from a point', actors: 0,
    params: { actors: [[], 'text'], from: [[4, 4], 'cell'], dur: [0.5, 0.1, 2] } },
  waltz: { family: 'motion', doc: 'circle a partner in triple-metre turns', actors: 1,
    params: { partner: [null, ['a', 'b', 'c']], turns: [2, 1, 4] } },
  touch: { family: 'relationship', doc: "two actors' cells coincide; instant contact beat", actors: 1,
    params: { other: [null, ['a', 'b', 'c']] } },
  merge: { family: 'relationship', doc: 'two actors become one at a shared cell', actors: 1,
    params: { other: [null, ['a', 'b', 'c']], dur: [0.8, 0.1, 3] } },
  split: { family: 'relationship', doc: 'one actor becomes two, flying to separate cells; the ghost half lingers', actors: 1,
    params: { to: [[[3, 4], [5, 4]], 'text'], dur: [0.8, 0.1, 3], hold: [4, 0, 10] } },
  keepDistance: { family: 'relationship', doc: 'actor is held apart from a target, never closing', actors: 1,
    params: { target: [null, ['a', 'b', 'c']], gap: [3, 1, 6] } },
  swapSize: { family: 'relationship', doc: 'two actors trade their current scales', actors: 1,
    params: { other: [null, ['a', 'b', 'c']], dur: [0.5, 0.1, 2] } },
  fillRing: { family: 'crowd', doc: 'light a concentric ring of chorus dots around a centre', actors: 0,
    params: { center: [[4, 4], 'cell'], ring: [1, 0, 4], color: ['#fff', 'text'] } },
  fillColumn: { family: 'crowd', doc: 'light a column top to bottom in sequence, or bottom to top', actors: 0,
    params: { col: [4, 0, 8], stepDur: [0.3, 0.05, 1], dir: ['down', ['down', 'up']] } },
  closeIn: { family: 'crowd', doc: 'a ring or crowd contracts toward its centre', actors: 0,
    params: { center: [[4, 4], 'cell'], dur: [1.5, 0.2, 4] } },
  curtainParts: { family: 'crowd', doc: 'two chorus blocks slide apart to reveal the centre', actors: 0,
    params: { dur: [1, 0.2, 3] } },
  colourWash: { family: 'state', doc: 'flood the grid or a group to one colour/brightness', actors: 'grid',
    params: { color: ['#fff', 'text'], dur: [2, 0.2, 5] } },
  dim: { family: 'state', doc: 'reduce brightness without changing scale', actors: 1,
    params: { to: [0.3, 0, 1], dur: [1, 0.1, 3] } },
  burnEmber: { family: 'state', doc: 'colour bleeds to ember red then dims to nothing', actors: 1,
    params: { dur: [2, 0.5, 5] } },
  zoomTo: { family: 'camera', doc: 'centre and scale the camera on an actor', actors: 1,
    params: { target: [null, ['a', 'b', 'c']], zoom: [1.5, 1, 3], dur: [1, 0.1, 3] } },
  shake: { family: 'camera', doc: 'short high-frequency camera jitter', actors: 0,
    params: { amount: [6, 1, 20], dur: [0.3, 0.1, 1] } },
  drift: { family: 'camera', doc: 'slow unforced camera pan with no target', actors: 0,
    params: { to: [[4, 4], 'cell'], dur: [3, 0.5, 8] } },
  snapCut: { family: 'camera', doc: 'instant camera reframe, no tween', actors: 1,
    params: { target: [null, ['a', 'b', 'c']], zoom: [1.5, 1, 3] } },
  label: { family: 'text', doc: 'a bracket or tag beside an actor', actors: 1,
    params: { text: ['', 'text'], dur: [0.4, 0.1, 2] } },
  speech: { family: 'text', doc: 'black box, white uppercase text, on an actor', actors: 1,
    params: { text: ['', 'text'], hold: [1, 0.2, 4] } },
  stutter: { family: 'time', doc: 'rapid visual retrigger, same cell, no travel', actors: 1,
    params: { beats: [4, 1, 12] } },
  slow: { family: 'time', doc: 'a held breath: the grid dips and holds (approximation — the tween engine has no live timeScale)', actors: 0,
    params: { dur: [1, 0.1, 4] } },
  drum: { family: 'sound', doc: 'noise-buffer percussion hit from a named pattern', actors: 0,
    params: { pattern: ['kick', ['kick', 'snare', 'hat', 'heartbeat']], vol: [0.15, 0, 0.4] } },
  echoVoice: { family: 'sound', doc: 'replay the last phrase quieter, on a different timbre', actors: 1,
    params: { delay: [0.3, 0, 1], voice: [null, ['tenor', 'soprano', 'bass', 'arp']] } },
};
