/* Reads src/engine/meta.js, dist/sizes.json (per-gesture gzipped bytes, from
   the build) and synth.js's instrument objects and transform names, and
   writes docs/engine-api.md: one table per gesture family, then the
   instruments, the transforms, and the score time formats.
   Run as the build's postbuild step. If dist/sizes.json isn't there yet
   (the playground agent's build change hasn't landed), print '?' for bytes
   and carry on rather than failing the build. */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const meta = require(path.join(ROOT, 'src/engine/meta.js'));

let sizes = {};
const sizesPath = path.join(ROOT, 'dist/sizes.json');
if (fs.existsSync(sizesPath)) {
  try { sizes = JSON.parse(fs.readFileSync(sizesPath, 'utf8')); }
  catch (e) { console.warn('gen-api: dist/sizes.json unreadable, printing ? for bytes'); }
} else {
  console.warn('gen-api: dist/sizes.json missing, printing ? for bytes');
}

const synthSrc = fs.readFileSync(path.join(ROOT, 'src/engine/synth.js'), 'utf8');

// O.inst = { name: { field: value, ... }, ... } -- pull the top-level
// instrument names and their field lists by regex, good enough for a docs
// table (values may be arrays/expressions; we just list field names).
function parseInstruments(src) {
  const start = src.indexOf('O.inst = {');
  if (start < 0) return [];
  const bodyStart = start + 'O.inst = {'.length;
  // find the matching close brace for the outer O.inst object
  let depth = 1, i = bodyStart;
  while (depth > 0 && i < src.length) {
    if (src[i] === '{') depth++;
    else if (src[i] === '}') depth--;
    i++;
  }
  const body = src.slice(bodyStart, i - 1);
  const insts = [];
  const nameRe = /(\w+):\s*\{/g;
  let m;
  while ((m = nameRe.exec(body))) {
    const name = m[1];
    let d = 1, j = m.index + m[0].length;
    const fieldStart = j;
    while (d > 0 && j < body.length) {
      if (body[j] === '{') d++;
      else if (body[j] === '}') d--;
      j++;
    }
    const fieldSrc = body.slice(fieldStart, j - 1);
    const fields = [...fieldSrc.matchAll(/(\w+):/g)].map((x) => x[1]);
    insts.push({ name, fields });
    nameRe.lastIndex = j;
  }
  return insts;
}

function parseTransforms(src) {
  const m = /O\.T\s*=\s*\{([\s\S]*?)\n\};/.exec(src);
  if (!m) return [];
  return [...m[1].matchAll(/(\w+):/g)].map((x) => x[1]);
}

const instruments = parseInstruments(synthSrc);
const transforms = parseTransforms(synthSrc);

function fmtDefault(d) {
  if (d === null || d === undefined) return '—';
  if (typeof d === 'string') return `'${d}'`;
  if (Array.isArray(d)) return JSON.stringify(d);
  return String(d);
}

// A param entry is [default, ...rest]. rest is: [min, max] (two numbers) for
// a slider, [options] (one array) for a select, or a single string 'cell' /
// 'text' / 'numeral' for those control types. No rest means no control (a
// fixed value, e.g. cue's hold).
function fmtParam(name, arr) {
  const [def, ...rest] = arr;
  let ctrl = '';
  if (rest.length === 2 && typeof rest[0] === 'number') ctrl = `${rest[0]}–${rest[1]}`;
  else if (rest.length === 1 && Array.isArray(rest[0])) ctrl = rest[0].map((x) => `\`${x}\``).join(', ');
  else if (rest.length === 1) ctrl = String(rest[0]);
  return `\`${name}\` (${fmtDefault(def)}${ctrl ? ', ' + ctrl : ''})`;
}

function bytesFor(name) {
  if (sizes && typeof sizes[name] === 'number') return String(sizes[name]);
  return '?';
}

const families = {};
for (const [name, g] of Object.entries(meta)) {
  (families[g.family] = families[g.family] || []).push({ name, ...g });
}

let out = '# Engine API\n\n';
out += 'Generated by `tools/gen-api.js` from `src/engine/meta.js`, `dist/sizes.json` and `src/engine/synth.js`. Do not edit by hand.\n\n';

for (const family of Object.keys(families).sort()) {
  out += `## ${family}\n\n`;
  out += '| name | doc | actors | params (default, control) | bytes |\n';
  out += '| --- | --- | --- | --- | --- |\n';
  for (const g of families[family]) {
    const params = Object.entries(g.params || {})
      .map(([k, arr]) => fmtParam(k, arr))
      .join('; ') || '—';
    out += `| \`${g.name}\` | ${g.doc} | ${g.actors} | ${params} | ${bytesFor(g.name)} |\n`;
  }
  out += '\n';
}

out += '## Instruments\n\n';
if (instruments.length) {
  out += '| name | fields |\n| --- | --- |\n';
  for (const inst of instruments) out += `| \`${inst.name}\` | ${inst.fields.map((f) => `\`${f}\``).join(', ')} |\n`;
} else {
  out += '(could not parse `O.inst` from synth.js)\n';
}
out += '\n';

out += '## Transforms\n\n';
out += transforms.length ? transforms.map((t) => `\`${t}\``).join(', ') + '\n\n' : '(could not parse `O.T` from synth.js)\n\n';

out += '## Score time formats\n\n';
out += [
  '- A number: seconds from the start of the intro.',
  "- `'b.q'`: bar and beat inside the re-version (bar 1 beat 1 is the first beat after the intro); beats are quarter notes, bars are four beats.",
  "- `'oN'`: N seconds into the outro.",
].join('\n') + '\n';

fs.mkdirSync(path.join(ROOT, 'docs'), { recursive: true });
fs.writeFileSync(path.join(ROOT, 'docs/engine-api.md'), out);
console.log(`gen-api: wrote docs/engine-api.md (${Object.keys(meta).length} gestures, ${instruments.length} instruments, ${transforms.length} transforms)`);
